src/Clean.Architecture.Web/ViewModels/ProjectViewModel.cs
using System.Collections.Generic;

namespace Clean.Architecture.Web.ViewModels
{
    public class ProjectViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<ToDoItemViewModel> Items = new();
    }
}

src/Clean.Architecture.Web/ViewModels/ToDoItemViewModel.cs
using Clean.Architecture.Core.ProjectAggregate;

namespace Clean.Architecture.Web.ViewModels
{
    public class ToDoItemViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsDone { get; private set; }

        public static ToDoItemViewModel FromToDoItem(ToDoItem item)
        {
            return new ToDoItemViewModel()
            {
                Id = item.Id,
                Title = item.Title,
                Description = item.Description,
                IsDone = item.IsDone
            };
        }
    }
}

src/Clean.Architecture.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Clean.Architecture.Web.Controllers
{
    /// <summary>
    /// A sample MVC controller that uses views.
    /// Razor Pages provides a better way to manage view-based content, since the behavior, viewmodel, and view are all in one place,
    /// rather than spread between 3 different folders in your Web project. Look in /Pages to see examples.
    /// See: https://ardalis.com/aspnet-core-razor-pages-%E2%80%93-worth-checking-out/
    /// </summary>
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/Clean.Architecture.Web/Controllers/ProjectController.cs
using System.Linq;
using System.Threading.Tasks;
using Clean.Architecture.Core;
using Clean.Architecture.Core.ProjectAggregate;
using Clean.Architecture.Core.ProjectAggregate.Specifications;
using Clean.Architecture.SharedKernel.Interfaces;
using Clean.Architecture.Web.ApiModels;
using Clean.Architecture.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Clean.Architecture.Web.Controllers
{
    [Route("[controller]")]
    public class ProjectController : Controller
    {
        private readonly IRepository<Project> _projectRepository;

        public ProjectController(IRepository<Project> projectRepository)
        {
            _projectRepository = projectRepository;
        }

        // GET project/{projectId?}
        [HttpGet("{projectId:int}")]
        public async Task<IActionResult> Index(int projectId = 1)
        {
            var spec = new ProjectByIdWithItemsSpec(projectId);
            var project = await _projectRepository.GetBySpecAsync(spec);

            var dto = new ProjectViewModel
            {
                Id = project.Id,
                Name = project.Name,
                Items = project.Items
                            .Select(item => ToDoItemViewModel.FromToDoItem(item))
                            .ToList()
            };
            return View(dto);
        }
    }
}

src/Clean.Architecture.Web/Pages/ProjectDetails/Incomplete.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Clean.Architecture.Core.ProjectAggregate;
using Clean.Architecture.Core.ProjectAggregate.Specifications;
using Clean.Architecture.SharedKernel.Interfaces;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Clean.Architecture.Web.Pages.ToDoRazorPage
{
    public class IncompleteModel : PageModel
    {
        private readonly IRepository<Project> _repository;

        public List<ToDoItem> ToDoItems { get; set; }

        public IncompleteModel(IRepository<Project> repository)
        {
            _repository = repository;
        }

        public async Task OnGetAsync()
        {
            var projectSpec = new ProjectByIdWithItemsSpec(1); // TODO: get from route
            var project = await _repository.GetBySpecAsync(projectSpec);
            var spec = new IncompleteItemsSpec();

            ToDoItems = spec.Evaluate(project.Items).ToList();
        }
    }
}

src/Clean.Architecture.Web/Pages/ProjectDetails/Index.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using Clean.Architecture.Core.ProjectAggregate;
using Clean.Architecture.Core.ProjectAggregate.Specifications;
using Clean.Architecture.SharedKernel.Interfaces;
using Clean.Architecture.Web.ApiModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Clean.Architecture.Web.Pages.ToDoRazorPage
{
    public class IndexModel : PageModel
    {
        private readonly IRepository<Project> _repository;

        [BindProperty(SupportsGet = true)]
        public int ProjectId { get; set; }
        public string Message { get; set; } = "";

        public ProjectDTO Project { get; set; }

        public IndexModel(IRepository<Project> repository)
        {
            _repository = repository;
        }

        public async Task OnGetAsync()
        {
            var projectSpec = new ProjectByIdWithItemsSpec(ProjectId);
            var project = await _repository.GetBySpecAsync(projectSpec);

            if(project == null)
            {
                Message = "No project found.";
                return;
            }

            Project = new ProjectDTO
            {
                Id = project.Id,
                Name = project.Name,
                Items = project.Items
                .Select(item => ToDoItemDTO.FromToDoItem(item))
                .ToList()
            };
        }
    }
}

src/Clean.Architecture.Web/Pages/ProjectDetails/Incomplete.cshtml
@page
@model Clean.Architecture.Web.Pages.ToDoRazorPage.IncompleteModel

<h2>Incomplete To Do Items (Razor Page)</h2>
<ul>
    @foreach (var item in Model.ToDoItems)
    {
        <li>
            @item.Title @if (item.IsDone)
        {
            <span>DONE!</span>
        }
        else
        {
        <span>NOT DONE</span>
        }
            <br />@item.Description
        </li>
    }
</ul>

src/Clean.Architecture.Web/Pages/ProjectDetails/Index.cshtml
@page "{ProjectId}"
@model Clean.Architecture.Web.Pages.ToDoRazorPage.IndexModel

@if (!String.IsNullOrEmpty(Model.Message))
{
    <h2>@Model.Message</h2>
}
else
{

<h2>Project (Razor Page)</h2>

<h3>Name: @Model.Project.Name</h3>

<b>Items:</b>

<ul>
    @foreach (var item in Model.Project.Items)
    {
        <li>
            @item.Title @if (item.IsDone)
            {
                <span>DONE!</span>
            }
            else
            {
                <span>NOT DONE</span>
            }
            <br />@item.Description
        </li>
    }
</ul>
}

src/Clean.Architecture.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Clean DDD Architecture Sample";
}
<div class="row">
    <div class="col-md-4">
        <h3>Using this template</h3>
        <p>
            This template includes support for:
            <ul>
                <li>APIs using API Endpoints (in the /Endpoints folder)</li>
                <li>APIs using Controllers (in the /Api and /ApiModels folders)</li>
                <li>Pages using Razor Pages (in the /Pages folder and /Views/Shared folder)</li>
                <li>Pages using Controllers and Views (in the /Controllers, /ViewModels, and /Views folders - keep /Views/Shared for Razor Pages though)</li>
            </ul>
            Choose which features you will use for your project and delete the ones you will not use.
        </p>
        <p>
            Provide feedback and report issues in the <a href="https://github.com/ardalis/CleanArchitecture">project's GitHub repository</a>; ask questions using the <a href="https://stackoverflow.com/questions/tagged/ardalis-cleanarchitecture?tab=Newest">ardalis-cleanarchitecture tag on StackOverflow</a>.
        </p>
    </div>
    <div class="col-md-4">
        <h3>APIs</h3>
        Shows both Controller and Endpoint APIs.
        <ul>
            <li><a href="/swagger">API Documentation (Swagger)</a></li>
        </ul>
        <h3>Projects (using Razor Pages)</h3>
        <ul>
            <li><a asp-page="/ProjectDetails/Index" asp-route-ProjectId="1">Show Project ID:1 and its To Do Items</a></li>
            <li><a asp-page="/ProjectDetails/Incomplete">List Incomplete To Do Items</a></li>
        </ul>
        <h3>Projects (using MVC Views)</h3>
        <ul>
            <li><a asp-area="" asp-controller="Project" asp-action="Index" asp-route-projectId="1">Show Project ID:1 and its To Do Items</a></li>
        </ul>
    </div>
    <div class="col-md-4">
        <h3>About the Author</h3>
        <ul>
            <li><a href="https://ardalis.com">Blog - Ardalis.com</a></li>
            <li><a href="https://twitter.com/ardalis">Twitter - @@ardalis</a></li>
            <li><a href="https://github.com/ardalis">GitHub</a></li>
            <li><a href="https://www.pluralsight.com/authors/steve-smith">Lastest Pluralsight Courses</a></li>
        </ul>
        <h3>More resources for this template</h3>
        <ul>
            <li><a href="https://github.com/ardalis/CleanArchitecture">CleanArchitecture GitHub repository</a></li>
            <li><a href="https://stackoverflow.com/questions/tagged/ardalis-cleanarchitecture?tab=Newest">Ardalis-CleanArchitecture on Stack Overflow</a></li>
            <li><a href="https://www.pluralsight.com/courses/domain-driven-design-fundamentals">Domain-Driven Design Fundamentals Course (Pluralsight)</a></li>
            <li><a href="https://www.pluralsight.com/courses/n-tier-apps-part1">Creating N-Tier Applications in C# Course (Part 1) (Pluralsight)</a></li>
            <li><a href="https://www.pluralsight.com/courses/n-tier-csharp-part2">Creating N-Tier Applications in C# Course (Part 2) (Pluralsight)</a></li>
        </ul>
    </div>
</div>

src/Clean.Architecture.Web/Views/Project/Index.cshtml
@{
    ViewData["Title"] = "Project Details";
}
@model Clean.Architecture.Web.ViewModels.ProjectViewModel
<h2>Project (MVC View)</h2>

<h3>Name: @Model.Name</h3>

<b>Items:</b>

<ul>
    @foreach (var item in Model.Items)
    {
        <li>@item.Title<br />@item.Description</li>
    }
</ul>

src/Clean.Architecture.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Clean.Architecture.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Clean.Architecture.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Today.Year - Clean.Architecture.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.2.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

@await RenderSectionAsync("scripts", required: false).ConfigureAwait(false)
</body>
</html>